### PR TITLE
[WIP] Fix #69

### LINKED ISSUE #69: Only show `[LC] ...` part on popupmenu completions
Currently, when showing completions for Rust with the external popupmenu, I get this sort of thing happening, with the popupmenu showing only one item:

image

But in normal Neovim (in the terminal) it looks like this, with only the `[LC] ...` part showing and so I can see more items in the popupmenu:

image

One solution would be to only show the extra text on hover, like in [GNvim](https://github.com/vhakulinen/gnvim) after pressing `<C-S>` while hovering on a completion item:

image

EDIT: Note that this problem only happens with (potentially long) documentation on the corresponding completions. In some cases there are no problems. It's only for things like the Rust standard library which is well documented and thus has longer docs for each function.

### PR DESCRIPTION
**Pull request by smolck**
Just putting this here for now until I can finish it (hopefully later today).

@akiyosi I'd like to put show the `detailText` in a separate window next to the popupmenu when a popupmenu item is selected (making the popupmenu smaller if necessary), but I'm not really sure how to go about doing that. Would you mind helping me with that part of this PR?

Note that I've removed some comments and changed the formatting a bit; if that's an issue please let me know.

### CODE REVIEW

**Comment by akiyosi** [comment]
@smolck 
I am very grateful for your contribution.

I was looking at the gnvim popup menu and wondering how it could be implemented with goneovim.
Perhaps we need to process that merge the right side cells verticaly in qgridlayout.

Currentry, goneovim popupmenu is the following structure.

```
              0         1         2
     ||==================================== 
     ||
     ||  +-----------------------------+ 
     ||  | +------++-------++--------+ |
 i=0 ||  | | kind || menu  || detail | |
     ||  | +------++-------++--------+ |
     ||  | +------++-------++--------+ |
 i=1 ||  | | kind || menu  || detail | |
     ||  | +------++-------++--------+ |
```

From this state, I think that it is necessary to merge the cells on the right side of qgridlayout vertically, using the popup menu selection as a trigger.

```
              0         1         2
     ||==================================== 
     ||
     ||  +-----------------------------+ 
     ||  | +------++-------++--------+ |
 i=0 || >| | kind || menu  || detail | |
     ||  | +------++-------+| detail | |
     ||  | +------++-------+| detail | |
 i=1 ||  | | kind || menu  || detail | |
     ||  | +------++-------++--------+ |
```

If merging is difficult, we may need to adopt a more appropriate layout structure instead of qgridlayout.

**Comment by akiyosi** [comment]
Ummm, Or it may be more practical to embed it in a larger structure.
e.g.

```
 +---------------------------------------------------------+
 |  +-----------------------------+ +-----------------+ ++ |
 |  | +------++-------++--------+ | |                 | || |
 |  | | kind || menu  || detail | | |                 | || |
 |  | +------++-------++--------+ | |                 | || |
 |  | +------++-------++--------+ | |                 | || |
 |  | | kind || menu  || detail | | |                 | || |
 |  | +------++-------++--------+ | +-----------------+ || |
```

In this case, since the width is large, it seems better to consider processing such as hiding the column in the detail part.

**Comment by smolck** [comment]
> I am very grateful for your contribution.

Thanks! And no problem ;)

> Ummm, Or it may be more practical to embed it in a larger structure.
> e.g.
> 
> ```
>  +---------------------------------------------------------+
>  |  +-----------------------------+ +-----------------+ ++ |
>  |  | +------++-------++--------+ | |                 | || |
>  |  | | kind || menu  || detail | | |                 | || |
>  |  | +------++-------++--------+ | |                 | || |
>  |  | +------++-------++--------+ | |                 | || |
>  |  | | kind || menu  || detail | | |                 | || |
>  |  | +------++-------++--------+ | +-----------------+ || |
> ```
> 
> In this case, since the width is large, it seems better to consider processing such as hiding the column in the detail part.

Yes, this is more what I was thinking (nice example by the way!). My problem is translating that to Qt code, since I’m not really sure what widgets to use, where to put them, etc.

**Comment by akiyosi** [comment]
> Yes, this is more what I was thinking (nice example by the way!). My problem is translating that to Qt code, since I’m not really sure what widgets to use, where to put them, etc.

This is simple changes to display detail text.
I think more adjustments are actually required.

``` diff
diff --git a/editor/popupmenu.go b/editor/popupmenu.go
index 6bbd41a..8a0837c 100644
--- a/editor/popupmenu.go
+++ b/editor/popupmenu.go
@@ -31,10 +31,13 @@ type PopupMenu struct {
 	scrollCol       *widgets.QWidget
 	x               int
 	y               int
+	detailLabel       *widgets.QLabel
 }
 
 // PopupItem is
 type PopupItem struct {
+	p          *PopupMenu
+
 	kindLabel  *widgets.QLabel
 	kindText   string
 	kind       string
@@ -47,7 +50,6 @@ type PopupItem struct {
 	menuTextRequest string
 
 	detailWidget      *widgets.QWidget
-	detailLabel       *widgets.QLabel
 	detailTextRequest string
 
 	selected        bool
@@ -69,9 +71,12 @@ func initPopupmenuNew() *PopupMenu {
 	scrollBar := widgets.NewQWidget(scrollCol, 0)
 	scrollBar.SetFixedWidth(5)
 
+	detailLabel := widgets.NewQLabel(nil, 0)
+
 	mainLayout := widgets.NewQHBoxLayout()
 	mainLayout.AddLayout(layout, 0)
 	mainLayout.AddWidget(scrollCol, 0, 0)
+	mainLayout.AddWidget(detailLabel, 0, 0)
 	mainLayout.SetContentsMargins(0, 0, 0, 0)
 	mainLayout.SetSpacing(0)
 
@@ -82,6 +87,15 @@ func initPopupmenuNew() *PopupMenu {
 	max := 15
 	var popupItems []*PopupItem
 
+	popup := &PopupMenu{
+		widget:    widget,
+		layout:    layout,
+		detailLabel: detailLabel,
+		total:     max,
+		scrollBar: scrollBar,
+		scrollCol: scrollCol,
+	}
+
 	margin := editor.config.Editor.Linespace/2 + 2
 	for i := 0; i < max; i++ {
 		kindWidget := widgets.NewQWidget(nil, 0)
@@ -102,40 +116,20 @@ func initPopupmenuNew() *PopupMenu {
 		kindLabel.SetContentsMargins(margin, margin, margin, margin)
 		kindLabel.SetObjectName("kindlabelpopup")
 
-		detailWidget := widgets.NewQWidget(nil, 0)
-		detailLayout := widgets.NewQHBoxLayout()
-		detailLayout.SetContentsMargins(margin, 0, margin, 0)
-
-		detailWidget.SetLayout(detailLayout)
-		detailWidget.SetObjectName("detailpopup")
-
-		detailLabel := widgets.NewQLabel(nil, 0)
-        detailLayout.AddWidget(detailLabel, 0, 0)
-
 		layout.AddWidget2(kindWidget, i, 0, 0)
 		layout.AddWidget2(menu, i, 1, 0)
 		layout.AddWidget2(kindLabel, i, 2, 0)
-		layout.AddWidget2(detailWidget, i, 3, 0)
 
 		popupItem := &PopupItem{
+			p:            popup,
 			kindLabel:    kindLabel,
 			kindWidget:   kindWidget,
 			kindIcon:     kindIcon,
 			menuLabel:    menu,
-			detailWidget: detailWidget,
-			detailLabel:  detailLabel,
 		}
 		popupItems = append(popupItems, popupItem)
 	}
-
-	popup := &PopupMenu{
-		widget:    widget,
-		layout:    layout,
-		items:     popupItems,
-		total:     max,
-		scrollBar: scrollBar,
-		scrollCol: scrollCol,
-	}
+	popup.items = popupItems
 
 	popup.widget.SetGraphicsEffect(util.DropShadow(-2, 6, 40, 200))
 
@@ -143,11 +137,11 @@ func initPopupmenuNew() *PopupMenu {
 }
 
 func (p *PopupMenu) updateFont(font *Font) {
+	p.detailLabel.SetFont(font.fontNew)
 	for i := 0; i < p.total; i++ {
 		popupItem := p.items[i]
 		popupItem.kindLabel.SetFont(font.fontNew)
 		popupItem.menuLabel.SetFont(font.fontNew)
-		popupItem.detailLabel.SetFont(font.fontNew)
 	}
 }
 
@@ -276,7 +270,12 @@ func (p *PopupMenu) selectItem(args []interface{}) {
 	}
 	for i := 0; i < p.showTotal; i++ {
 		popupItem := p.items[i]
-		popupItem.setSelected(selected == i+p.top)
+		isSelected := selected == i+p.top
+		popupItem.setSelected(isSelected)
+		if isSelected {
+			popupItem.p.detailLabel.SetText(popupItem.detailText)
+			popupItem.p.detailLabel.Show()
+		}
 	}
 }
 
@@ -308,17 +307,15 @@ func (p *PopupItem) updateMenu() {
 		if p.selected {
 			p.kindWidget.SetStyleSheet(fmt.Sprintf("background-color: %s;", editor.colors.selectedBg.StringTransparent()))
 			p.menuLabel.SetStyleSheet(fmt.Sprintf("background-color: %s;", editor.colors.selectedBg.StringTransparent()))
-			p.detailLabel.SetStyleSheet(fmt.Sprintf("background-color: %s;", editor.colors.selectedBg.StringTransparent()))
 			p.kindLabel.SetStyleSheet(fmt.Sprintf("background-color: %s;", editor.colors.selectedBg.StringTransparent()))
 
-			p.detailLabel.Show()
+			p.p.detailLabel.Show()
 		} else {
 			p.kindWidget.SetStyleSheet("background-color: rgba(0, 0, 0, 0);")
 			p.menuLabel.SetStyleSheet("background-color: rgba(0, 0, 0, 0);")
-			p.detailLabel.SetStyleSheet("background-color: rgba(0, 0, 0, 0);")
 			p.kindLabel.SetStyleSheet("background-color: rgba(0, 0, 0, 0);")
 
-			p.detailLabel.Hide()
+			p.p.detailLabel.Hide()
 		}
 	}
 	if p.menuTextRequest != p.menuText {
@@ -329,10 +326,8 @@ func (p *PopupItem) updateMenu() {
 		p.kindLabel.SetText(strings.Split(p.detailTextRequest, "¥n")[0])
 
 		p.detailText = p.detailTextRequest
-		p.detailLabel.SetText(p.detailText)
 	}
 	p.menuLabel.AdjustSize()
-	p.detailLabel.AdjustSize()
 	p.menuLabel.AdjustSize()
 }
 
@@ -431,7 +426,7 @@ func (p *PopupItem) hide() {
 	p.kindLabel.Hide()
 	p.kindIcon.Hide()
 	p.menuLabel.Hide()
-	p.detailLabel.Hide()
+	p.p.detailLabel.Hide()
 }
 
 func (p *PopupItem) show() {
```

**Comment by smolck** [comment]
Thanks! I've pushed you're changes. But as you said, there's still some tweaking that needs to happen. For starters, the popupmenu becomes quite long, which means in a smaller window this happens, where the detail text gets cut off:

image

We may wish to not show the `kindLabel` text by default unless that's set as an option in `~/.goneovim/setting.toml`. Then, you would only see the detail text on selection, and I think it would mostly fix this problem.

EDIT: So you would only see the function name (not the `[LC] ...` part) if nothing was selected, and then the detail text to the side if you selected an item.

**Comment by smolck** [comment]
We may also want to move the scrollbar when showing the detail text, or add some left padding to the detail text window:

image

**Comment by akiyosi** [comment]
I'm not very aggressive about increasing the config item in `setting.toml`.
I feel that it is good to hide the short description when selecting an item.

For example, we can hide the short description only when selecting an item with the following changes.

``` diff
diff --git a/editor/popupmenu.go b/editor/popupmenu.go
index 91523ca..f3681e7 100644
--- a/editor/popupmenu.go
+++ b/editor/popupmenu.go
@@ -269,14 +269,22 @@ func (p *PopupMenu) selectItem(args []interface{}) {
        if selected >= 0 && selected-p.top < 0 {
                p.scroll(-1)
        }
+       isSelected := false
        for i := 0; i < p.showTotal; i++ {
                popupItem := p.items[i]
-        isSelected := selected == i+p.top
-        popupItem.setSelected(isSelected)
-        if isSelected {
-            popupItem.p.detailLabel.SetText(popupItem.detailText)
-            popupItem.p.detailLabel.Show()
-        }
+               isSelected := selected == i+p.top
+               popupItem.setSelected(isSelected)
+               if isSelected {
+                   popupItem.p.detailLabel.SetText(popupItem.detailText)
+                   popupItem.p.detailLabel.Show()
+               }
+       }
+       if isSelected {
+               return
+       }
+       for i := 0; i < p.showTotal; i++ {
+               popupItem := p.items[i]
+               popupItem.kindLabel.SetText("")
        }
 }
```

BTW, With the changes I've presented the above, the long description disappears with inputting `<C-p>`. I haven't fully investigated the cause, but there seems to be a problem somewhere.

**Comment by akiyosi** [comment]
> We may also want to move the scrollbar when showing the detail text, or add some left padding to the detail text window:

Yes, I agree with this. The position of the scroll bar in the above implementation looks a little annoying.

**Comment by smolck** [comment]
> I feel that it is good to hide the short description when selecting an item.
> For example, we can hide the short description only when selecting an item with the following changes.

With the changes you mentioned, the disappearance of all of the short descriptions is somewhat abrupt. Here's a few other ways we could prevent the popupmenu from growing too large:
1) We could (I think?) limit the width of the popupmenu and cut off the text of each `kindLabel` as necessary to stay within that limit. Not sure how feasible this is.
2) We could display the `kindLabel` underneath the name of each function, instead of next to it.
3) This might be difficult, but we could (like the first point) limit the width of popupmenu and wrap the `kindLabel` text of each item underneath the `menuLabel` at a certain width, like in GNvim:

image

Do any of the above choices appeal to you, or would you like to continue forward with the changes you showed?

> BTW, With the changes I've presented the above, the long description disappears with inputting `<C-p>`. I haven't fully investigated the cause, but there seems to be a problem somewhere.

This happens for me as well.

**Comment by akiyosi** [comment]
Umm, it ’s a very difficult choice. The involvement of preference seems to be great.
I think `1.` is good.

**Comment by smolck** [comment]
I've pushed your changes with some slight modifications (most notably calling `kindLabel.Hide()` instead of `kindLabel.SetText("")` and setting a maximum size of the editor's width and height for the popupmenu). Turns out the removal of the `kindLabel`s when showing the description isn't as abrupt as I thought, so I've included that change.

I've also set the detail label to wrap it's text, as I said in the commit message, so now all the text is visible in the side window.

The `<C-p>` problem still exists; I think the cause is that the `kindIcon`s in each popupitem gets quite large and fills up the popupmenu, so that the `detailLabel` isn't visible anymore. Not sure why that's happening.....

Also, the `kindLabel` text for the first item (and sometimes more than the first I think) disappears after selecting some items in the pmenu, closing it and reopening it, like this (note the lack of a label with `[LC] ...` in the first popupitem):

image

**Comment by clason** [comment]
I don't want to derail the discussion, but I'd like to point out that there are language servers that put useful (short) information into the `kind` field that would be useful to show for all items. (Blessing and curse of LSP: the client has to support a very diverse range of servers, and assuming desired behavior from one or even a few will make others unhappy...)

So I'd strongly suggest making hiding the kind configurable. (Arguably, that sort of thing should be done by the client and not the GUI, since one might wish to use different servers for different file types.)

**Comment by akiyosi** [comment]
I added branch https://github.com/akiyosi/goneovim/tree/improve-popupmenu.
This branch is based on https://github.com/smolck/goneovim/tree/stop-showing-full-docstrings-in-pmenu with the following changes
* Add config item of popupmenu
* Fixed an issue where the icon corresponding to the type could not be handled properly with the switch statement
* Added `info` handling among `popupmenu_show` items. (See https://github.com/neovim/neovim/blob/master/runtime/doc/ui.txt)
* Little code refactoring

It ’s still WIP.
We mayl need to adjust the default width of each column, and need a little UI tweak.

**Comment by smolck** [comment]
Looks good to me! 👍 I guess this can be closed now.

**Comment by smolck** [comment]
@akiyosi Does pressing `<C-p>` still cause the info text to disappear in https://github.com/akiyosi/goneovim/tree/improve-popupmenu ?

**Comment by akiyosi** [comment]
Umm, I fixed the problem with `<C-p>`, but is the problem still occurring?
By the way, `showDetail` is false by default currently.

**Comment by smolck** [comment]
> Umm, I fixed the problem with `<C-p>`, but is the problem still occurring?

I don’t know, I haven’t tested the branch, just wanted to know if it still happens for you.

> By the way, `showDetail` is false by default currently.

Is this the flag that determines whether the `[LC] ...` part is shown when no items are selected? If so, to mirror Neovim (which shows that by default), you may want to default that to `true`.

**Comment by akiyosi** [comment]
> I don’t know, I haven’t tested the branch, just wanted to know if it still happens for you.

ah huh, I fixed it :)

> Is this the flag that determines whether the [LC] ... part is shown when no items are selected? If so, to mirror Neovim (which shows that by default), you may want to default that to true.

the `showDetail` flag is enable/disable showing `info` part of the items currently.
Should `menu` part(such as `[LC] ...`) be included?

**Comment by smolck** [comment]
> ah huh, I fixed it :)

Great! I'm curious, what was causing it?

> the `showDetail` flag is enable/disable showing `info` part of the items currently.
> Should `menu` part(such as `[LC] ...`) be included?

I'd say yes since it allows the user finer control over the editor, even though I doubt many people would change that setting (assuming it defaults to `true`).

**Comment by akiyosi** [comment]
> I'd say yes since it allows the user finer control over the editor, even though I doubt many people would change that setting (assuming it defaults to true).

Okey, I will fix it.

**Comment by akiyosi** [comment]
I've merged`menu` part into detailed text field and adjusted some UI.
How about it?

スクリーンショット 2019-11-07 23 05 57

**Comment by smolck** [comment]
Looks great! Great work! 👏

Would you mind posting a screenshot of the popupmenu when no items are selected?

**Comment by akiyosi** [comment]
Like this.
If you don't select an item, nothing is displayed (it isn't hidden)
スクリーンショット 2019-11-07 23 17 47

**Comment by smolck** [comment]
> Like this.
> If you don't select an item, nothing is displayed (it isn't hidden)

Great! Only thing is, in that screenshot it looks like the `[LC] ...` part gets cut off and doesn’t go the full length of the popupmenu. Do you know why that is happening?

**Comment by akiyosi** [comment]
> Great! Only thing is, in that screenshot it looks like the [LC] ... part gets cut off and doesn’t go the full length of the popupmenu. Do you know why that is happening?

That is a simple reason. A fixed-length width derived from the config file was set for each part other than the word part of the `popupmenu_show` event. If you want to display the full string, you need to specify a sufficient length in the config file.

**Comment by smolck** [comment]
> That is a simple reason. A fixed-length width derived from the config file was set for each part other than the word part of the `popupmenu_show` event. If you want to display the full string, you need to specify a sufficient length in the config file.

Ah, gotcha. Maybe it would be a good idea to default that value to the width of the popupmenu so as much of the `[LC] ...` part as possible is shown by default?

**Comment by akiyosi** [comment]
Should I increase the default value?
I annoy the proper default value.

**Comment by smolck** [comment]
> Should I increase the default value?
> I have no idea the proper default value.

My guess would be to go as large as possible (so the popupmenu’s width) by default so that as much of the `[LC] ...` part is shown as possible. So, I’d say yes and if people don’t like it they can lower the width in the config file, rather than having to increase it right away.

**Comment by akiyosi** [comment]
I see.
I have continued to think about it, but the contents of the items and the visibility of each column, and their lengths, are likely to need a little more consideration. For example, normal vim completion may have no menu or info information, and LSP detailed text may pop up at the top of the completion menu when the completion menu is cut off by a window.

Umm...

**Comment by smolck** [comment]
> I see.
> I have continued to think about it, but the contents of the items and the visibility of each column, and their lengths, are likely to need a little more consideration. For example, normal vim completion may have no `menu` or `info` information, . . .

What happens right now when there is no menu/info information?

> . . . and LSP detailed text may pop up at the top of the completion menu when the completion menu is cut off by a window.

Could you screenshot an example of this?

**Comment by befedo** [comment]
> I've merged`menu` part into detailed text field and adjusted some UI.
> How about it?
> 
> スクリーンショット 2019-11-07 23 05 57

Hi there,

I know this is not issue related, but how could one define to draw those litle icons in front of the `popupmenu`?

This looks really amazing, thumbs up ...

**Comment by smolck** [comment]
> I know this is not issue related, but how could one define to draw those litle icons in front of the `popupmenu`?

Hello! Do you mean define which icons are used, tell GoNeovim to draw the icons on the other side of the popupmenu, or have I misunderstood?

**Comment by befedo** [comment]
> > I know this is not issue related, but how could one define to draw those litle icons in front of the `popupmenu`?
> 
> Hello! Do you mean define which icons are used, tell GoNeovim to draw the icons on the other side of the popupmenu, or have I misunderstood?

Hi,

Simply draw the icons in front (like in the pictore above). This dosn't happen on my config thus I thought it's config related.

**Comment by smolck** [comment]
Ah, gotcha. Do you have

```
[Editor]
ExtPopupmenu = true
```

in `~/.goneovim/settings.toml`?

**Comment by befedo** [comment]
Yes, I have ...

I've also got icons but they look like this:
icon

I've also got [coc.nvim](https://github.com/neoclide/coc.nvim) as provider.

**Comment by smolck** [comment]
Could you try forking and running this branch? https://github.com/akiyosi/goneovim/tree/improve-popupmenu 

Alternatively, you could wait for the 0.4.1 release. There have been some slight UI changes in that branch which I presume includes the different icons. 

From https://github.com/akiyosi/goneovim/pull/73#issuecomment-551095427 (emphasis added):
> I've merged`menu` part into detailed text field and **adjusted some UI.**

**Comment by befedo** [comment]
> EDIT 2: Sorry for all the (potentially confusing) edits @befedo. The problem is likely coc.nvim or your language server; GoNeovim is unsure what type the completion/s is/are, so it doesn’t display the icons (since they are type-related). This could be a result of GoNeovim not supporting coc.nvim, your language server not sending over the type info to coc.nvim, or _maybe_ coc.nvim not understanding what the language server is sending over (not 100% sure that’s a possibility here). Unfortunately, I don’t really have time ATM to dig further into this, so if you want I can @ you later after I’ve had the time to investigate. Sorry again!

Hi there,

I think I resolved it. I've got this in my CocConfig:
```{json}
{
  "suggest.completionItemKindLabels": {
    "function": "\uf794",
    "method": "\uf6a6",
    "variable": "\uf71b",
    "constant": "\uf8ff",
    "struct": "\ufb44",
    "class": "\uf0e8",
    "interface": "\ufa52",
    "text": "\ue612",
    "enum": "\uf435",
    "enumMember": "\uf02b",
    "module": "\uf668",
    "color": "\ue22b",
    "property": "\ufab6",
    "field": "\uf93d",
    "unit": "\uf475",
    "file": "\uf471",
    "value": "\uf8a3",
    "event": "\ufacd",
    "folder": "\uf115",
    "keyword": "\uf893",
    "snippet": "\uf64d",
    "operator": "\uf915",
    "reference": "\uf87a",
    "typeParameter": "\uf278",
    "default": "\uf29c"
  }
}
```
Which couldn't be resolved by the [popupmenu](https://github.com/akiyosi/goneovim/blob/improve-popupmenu/editor/popupmenu.go#L478-L516). After changing those unicode chars to words (like 'func') everithing works as expected.
But damn there where much KindLabels emitted by coc.nvim.

Thanks for your response and time, and also sorry for the noise.

Best regards, and keep on going this looks really amazing!

**Comment by smolck** [comment]
No problem! Glad you figured it out!

**Comment by akiyosi** [comment]
@smolck
> What happens right now when there is no menu/info information?

It was a long horizontal menu that displayed only `word` part.
I solved this problem with the commit 836b74a.
This commit hides the `info` part and displays it with the `menu` part in the detail text label.

Here is the screenshots
スクリーンショット 2019-11-08 23 24 35
スクリーンショット 2019-11-08 23 24 53


The position change process when the detailed text label is cut in the window will be skipped in this improvement. Because it is a little complicated.

**Comment by smolck** [comment]
Looks good to me 👍 Great work!

**Pull request closed without merging**
